import Avatar from '@/components/common/avatar/avatar';
import HomeLeft from '@/components/home/homeLeft/HomeLeft';
import HomeRight from '@/components/home/homeRight/HomeRight';
import CommentBox from '@/components/modalComponents/CommentBox';
import Tweet from '@/components/tweet/tweet';
import connectMongo from '@/db/dbConnect';

import { useRouter } from 'next/router'
import React from 'react'
import style from "../../components/tweet/tweet.module.css"
import Button from '@/components/common/button/button';
import Head from 'next/head';
import CommentDB from '@/db/models/commentModel';
import PostDB from '@/db/models/postModel';



export async function getServerSideProps(context) {


    const { postid } = context.params;
    let post = null;
    let comments = null;
    try {
        await connectMongo();

        post = await PostDB.findOne({ _id: postid }).populate("owner");

        comments = await CommentDB.findOne({ head: postid }).populate({
            path: "nodes", populate: {
                path: "owner"
            }
        });


    } catch (error) {
        console.log(error);

    }





    return { props: { tweet: JSON.stringify(post), comments: JSON.stringify(comments) } }
}



export default function PostId({ tweet, comments }) {
    const router = useRouter()
    const tweetN = JSON.parse(tweet);
    const commentN = JSON.parse(comments);

    return (
        <>
            <Head>
                <title>Twitter</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/fav2.ico" />
            </Head>
            <main className='main'>
                <HomeLeft></HomeLeft>
                <div>
                    {tweetN && <Tweet tweet={tweetN}></Tweet>}
                    {tweetN && <CommentBox head={tweetN._id} ></CommentBox>}
                    {
                        commentN?.nodes?.map((comment, index) => {
                            const owner = comment.owner;
                            return <div className={style.tweet} key={comment._id}>
                                <section className={style.image}>
                                    <Avatar width='40px' image={owner?.image}></Avatar>
                                </section>
                                <section className={style.body}>
                                    <div className={style["header"]}>
                                        <div className={style.names}>
                                            <span className={style["name"]}>{owner?.username}</span>
                                            <span className={style["username"]}>{owner?.username}</span>
                                            <span>·</span>
                                        </div>
                                        <svg viewBox="0 0 24 24" aria-hidden="true" className={style.threeDot} ><g><path d="M3 12c0-1.1.9-2 2-2s2 .9 2 2-.9 2-2 2-2-.9-2-2zm9 2c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm7 0c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2z"></path></g></svg>
                                    </div>
                                    <div className={style.mainTweet}>{comment.body}</div>
                                    <Button style={{ width: "100px", paddingBlock: ".3rem", marginTop: "1rem" }} >Reply</Button>
                                </section >
                            </div>
                        })
                    }
                    <div>{tweet}</div>
                    <hr />
                    <div>{comments}</div>
                </div>
                <HomeRight></HomeRight>
                <style jsx>{`
                    .main{
                            width: 100%;
                            height: 100vh;
                            height: 100dvh;
                        display: grid;
                        grid-template-columns: 1fr var(--main-width) 1fr;
                        column-gap: 1rem;
                    }
            
            
                    `}</style>
            </main>
        </>
    )
}

// return { props: { tweet: JSON.parse(JSON.stringify(post)), comments: JSON.parse(JSON.stringify(comments)) } }
