import React, { useContext } from 'react'
import style from "../styles/Home.module.css"
import Image from 'next/image'
import TwitterLogo from '@/components/common/svg/TwitterLogo'
import Head from 'next/head'
import Tweet from '@/components/tweet/tweet'
import HomeMain from '@/components/home/homeMain/HomeMain'
import ModalComponent from '@/components/modal/ModalComponent'
import HomeLeft from '@/components/home/homeLeft/HomeLeft'

import Post from '@/components/common/post/post'
import { ModalContext } from '@/providers/ModalProvider'
import HomeRight from '@/components/home/homeRight/HomeRight'
import ModalSignInDiv from '@/components/modalComponents/signInDiv/ModalSignInDiv'
import ModalSignUpDiv from '@/components/modalComponents/signInDiv/ModalSignUpDiv'
// import SignUpDiv from '@/components/common/signUpDiv/SignUpDiv'


export default function Home() {
  const [ modal, ] = useContext(ModalContext)

  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fav2.ico" />
      </Head>
      <ModalComponent>
        {/* <h1>Hiiiiiii</h1> */}

        {modal.showPostEditor && <Post />}
        {modal.showSignIn && <ModalSignInDiv />}
        {modal.showSignUp && <ModalSignUpDiv></ModalSignUpDiv>}
      </ModalComponent>
      <main className={style.body}>
        {/* <TwitterLogo></TwitterLogo> */}


        {/* <section className={style.main} style={{ borderInline: "1px solid var( --border-color)" }}>

          <Tweet tweet={tweet}></Tweet>
          <Tweet tweet={tweet2}></Tweet>

        </section> */}
        <HomeLeft></HomeLeft>
        {/* <div></div> */}
        <HomeMain></HomeMain>
        <HomeRight></HomeRight>

      </main>
    </>
  )
}


